// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Finding struct {
	ID          int64
	ReviewRunID pgtype.UUID
	FilePath    string
	LineNumber  int32
	Severity    string
	Category    string
	Message     string
	CreatedAt   pgtype.Timestamptz
}

type Installation struct {
	ID          int64
	AccountName string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type PullRequest struct {
	ID           pgtype.UUID
	RepositoryID int64
	PrNumber     int32
	Title        pgtype.Text
	Author       pgtype.Text
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Repository struct {
	ID             int64
	InstallationID int64
	GithubRepoID   int64
	FullName       string
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type ReviewRun struct {
	ID                  pgtype.UUID
	PullRequestID       pgtype.UUID
	CommitSha           pgtype.Text
	Status              string
	Summary             string
	RiskScore           pgtype.Numeric
	MergeRecommendation string
	CreatedAt           pgtype.Timestamptz
}
