// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFinding = `-- name: CreateFinding :exec
INSERT INTO findings (review_run_id, file_path, line_number, severity, category, message)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateFindingParams struct {
	ReviewRunID pgtype.UUID
	FilePath    string
	LineNumber  int32
	Severity    string
	Category    string
	Message     string
}

func (q *Queries) CreateFinding(ctx context.Context, arg CreateFindingParams) error {
	_, err := q.db.Exec(ctx, createFinding,
		arg.ReviewRunID,
		arg.FilePath,
		arg.LineNumber,
		arg.Severity,
		arg.Category,
		arg.Message,
	)
	return err
}

const createInstallation = `-- name: CreateInstallation :one

INSERT INTO installations (id, account_name)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE SET updated_at = NOW()
RETURNING id, account_name, created_at, updated_at
`

type CreateInstallationParams struct {
	ID          int64
	AccountName string
}

// The -- name: FunctionName :one comment is the magic of sqlc. It tells the compiler to generate a Go function named CreateReviewRun that returns exactly :one row.
// Instead of writing Go code to insert data, I am writing annotated SQL.
func (q *Queries) CreateInstallation(ctx context.Context, arg CreateInstallationParams) (Installation, error) {
	row := q.db.QueryRow(ctx, createInstallation, arg.ID, arg.AccountName)
	var i Installation
	err := row.Scan(
		&i.ID,
		&i.AccountName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPullRequest = `-- name: CreatePullRequest :one
INSERT INTO pull_requests (repository_id, pr_number, title, author)
VALUES ($1, $2, $3, $4)
ON CONFLICT (repository_id, pr_number) DO UPDATE SET updated_at = NOW()
RETURNING id, repository_id, pr_number, title, author, status, created_at, updated_at
`

type CreatePullRequestParams struct {
	RepositoryID int64
	PrNumber     int32
	Title        pgtype.Text
	Author       pgtype.Text
}

func (q *Queries) CreatePullRequest(ctx context.Context, arg CreatePullRequestParams) (PullRequest, error) {
	row := q.db.QueryRow(ctx, createPullRequest,
		arg.RepositoryID,
		arg.PrNumber,
		arg.Title,
		arg.Author,
	)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.PrNumber,
		&i.Title,
		&i.Author,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReviewRun = `-- name: CreateReviewRun :one
INSERT INTO review_runs (pull_request_id, commit_sha, summary, risk_score, merge_recommendation)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, pull_request_id, commit_sha, status, summary, risk_score, merge_recommendation, created_at
`

type CreateReviewRunParams struct {
	PullRequestID       pgtype.UUID
	CommitSha           pgtype.Text
	Summary             string
	RiskScore           pgtype.Numeric
	MergeRecommendation string
}

func (q *Queries) CreateReviewRun(ctx context.Context, arg CreateReviewRunParams) (ReviewRun, error) {
	row := q.db.QueryRow(ctx, createReviewRun,
		arg.PullRequestID,
		arg.CommitSha,
		arg.Summary,
		arg.RiskScore,
		arg.MergeRecommendation,
	)
	var i ReviewRun
	err := row.Scan(
		&i.ID,
		&i.PullRequestID,
		&i.CommitSha,
		&i.Status,
		&i.Summary,
		&i.RiskScore,
		&i.MergeRecommendation,
		&i.CreatedAt,
	)
	return i, err
}
